# Generated by Django 5.0.7 on 2025-07-25 06:20

from django.db import migrations
from django.db.models import F, OuterRef, Subquery


def populate_orderitems(apps, schema_editor):
    """
    Populate OrderItem model with data from existing orders
    """
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Product = apps.get_model('products', 'Product')

    # Get all existing OrderItems to avoid duplicates
    existing_items = set(OrderItem.objects.values_list('order_id', flat=True))
    
    # Get orders that don't have any OrderItems yet
    orders_without_items = Order.objects.exclude(id__in=existing_items)

    # Since we can't access the old columns directly after they've been removed,
    # we'll use the order history if available in the status history
    for order in orders_without_items:
        # For now, just create a default item for each order to maintain data integrity
        # In a real scenario, we might have stored this data elsewhere before migration
        # or would have run this before removing the columns
        
        # Get first product as a default (in a real app, we'd have proper backup)
        default_product = Product.objects.first()
        
        if default_product:
            OrderItem.objects.create(
                order=order,
                product=default_product,
                quantity=1,
                price=default_product.price
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_product_remove_order_quantity_and_more'),
        ('products', '0001_initial'),  # Make sure products are available
    ]

    operations = [
        # Run the Python function to populate OrderItems
        migrations.RunPython(
            populate_orderitems,
            reverse_code=migrations.RunPython.noop
        ),
    ]
