# Generated by Django 5.2.4 on 2025-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_migrate_existing_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name for guest customers or override', max_length=100, null=True),
        ),
    ]
