# Generated by Django 5.2.4 on 2025-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='required_unit',
            field=models.CharField(default='g', help_text='Unit for the required quantity (e.g., ml, g, kg)', max_length=10),
        ),
    ]
