# Generated by Django 5.0.7 on 2025-07-29 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_inventory', '0001_initial'),
        ('products', '0003_product_deductable_productingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productingredient',
            options={'verbose_name': 'Product Ingredient', 'verbose_name_plural': 'Product Ingredients'},
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductIngredient', to='ingredient_inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deductable',
            field=models.BooleanField(default=False, help_text='If checked, selling this product will deduct ingredients from inventory'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='ingredient_inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of ingredient used per product unit', max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='productingredient',
            unique_together={('product', 'ingredient')},
        ),
    ]
