# Generated by Django 5.0.7 on 2025-07-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productingredient_options_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Remembers original stock when product becomes deductable', null=True),
        ),
    ]
