# Generated by Django 5.0.7 on 2025-07-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_original_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_stock',
        ),
    ]
