# Generated by Django 5.2.6 on 2025-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_original_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='required_unit',
            field=models.CharField(default='g', help_text='Unit for the required quantity (e.g., ml, g, kg)', max_length=10),
        ),
    ]
